#!/bin/sh
path=$1
config_path=$2
app_port=$3

create_initi_config() {
  sudo mkdir -p /var/cse/game-app
  sudo cp -f $path/game-service-0.0.1-SNAPSHOT.jar /var/cse/game-app
  sudo ln -sf /var/cse/game-app/game-service-0.0.1-SNAPSHOT.jar /etc/init.d/game-app.jar
  sudo chmod 775 /etc/init.d/game-app.jar
  sudo cp -f $config_path/game-service-0.0.1-SNAPSHOT.conf /var/cse/game-app
}

prepare_game_yml () {
  sudo sed 's/${deploy_port}/'$app_port'/' $config_path/base.yml > /var/cse/game-app/game-app.yml
}

check_health () {

  status="Pending"

  local attemp=1
  max_attemps=5
  delay=5

  while [ "$status" != "UP" ] && [ "$attemp" -le "$max_attemps" ];  do
    echo "Attemp: $attemp/$max_attemps"
    status=$(curl http://localhost:$app_port/actuator/health | grep -oi '"status":"up"' | sed 's/\"//g' | awk -F':' '{ print $2 }' )

    echo "Waiting: $delay seconds to retry"
    sleep $delay

    attemp=`expr $attemp + 1`
  done

  if [ "$status" = "UP" ]; then
    echo "Service check status: SUCCESS"
  else
    echo "Service check status: FAILED"
    exit 1
  fi
}

start_service() {
  /etc/init.d/game-app.jar start
}

stop_service() {
  /etc/init.d/game-app.jar stop
}

restart_service() {
  /etc/init.d/game-app.jar restart
}

#Preparing configuration
create_initi_config

#Prepare game.yml
prepare_game_yml

#Starting service
start_service

#Check service status
check_health
